<?php

namespace English\DescriptionsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionRepository extends EntityRepository
{
    public function findDescriptionByCallTerm ($call, $term){
        return $this->createQueryBuilder('d')
            ->where('d.callNumber LIKE :call and d.term = :term')
            ->setParameter('call', $call)
            ->setParameter('term', $term)
            ->getQuery()
            ->getResult();
    }
}
