<?php

namespace English\DescriptionsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionRepository extends EntityRepository
{
}