<?php

namespace English\FilesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRepository extends EntityRepository
{
    /**
     * find newsletter label
     */
    public function findNewsletterLabel()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT l  FROM EnglishFilesBundle:Label l WHERE l.name = 'newsletter' ")
            ->getSingleResult();
    }
}
