<?php

namespace English\PeopleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailRepository extends EntityRepository
{
    public function findType($type)
    {
        if($type=='current') {
            return $this->getEntityManager()
                ->createQuery("SELECT d FROM EnglishPeopleBundle:Detail d WHERE d.endterm is null")
                ->getResult();
        }
        else {
            return $this->getEntityManager()
                ->createQuery("SELECT d FROM EnglishPeopleBundle:Detail d WHERE d.endterm is not null")
                ->getResult();
        }



    }
}
