<?php

namespace English\PeopleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailRepository extends EntityRepository
{
}
