<?php

namespace English\MentorsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MentorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentorRepository extends EntityRepository
{
}