<?php

namespace English\MajorsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoursRepository extends EntityRepository
{
}