<?php

namespace English\MajorsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MajorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MajorRepository extends EntityRepository
{
}