<?php

namespace English\SpotlightBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpotlightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotlightRepository extends EntityRepository
{
}