<?php

namespace English\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HelpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelpRepository extends EntityRepository
{
        public function listHelp()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT h from EnglishHomeBundle:Help h ORDER BY h.sortorder')->getResult();
    }  
}