<?php

namespace English\DawgspeakBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefRepository extends EntityRepository
{
}