<?php

namespace English\GradinfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GradinfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradinfoRepository extends EntityRepository
{
}