<?php

namespace English\GradnotesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GradnotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradnotesRepository extends EntityRepository
{
}