<?php

namespace English\MajornotesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MajornoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MajornoteRepository extends EntityRepository
{
}