<?php

namespace English\SlideshowBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SlideshowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideshowRepository extends EntityRepository
{
}