<?php

namespace English\TermBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermRepository extends EntityRepository
{
    public function findTermsSorted()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t from EnglishTermBundle:Term t ORDER BY t.term DESC')
            ->getResult();
    }

    public function findCurrentTerm()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM English\TermBundle\Entity\Term t WHERE t.type = 2')
            ->getSingleResult();
    }
}