<?php

namespace English\AdvisorsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvisorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvisorRepository extends EntityRepository
{
}