<?php

namespace English\DonateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonateRepository extends EntityRepository
{
}