<?php

namespace English\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    /**
     * find pages for menu
     */
    public function findPageMenu($section)
    {
            return $this->getEntityManager()
                ->createQuery('SELECT p  FROM EnglishPagesBundle:Page p WHERE p.parent IS NULL AND p.section = ?1 ORDER BY p.sortorder')
                ->setParameter('1',$section)->getResult();
    }
}
