<?php

namespace English\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    /**
     * find pages for menu
     */
    public function  findPageMenu($section) {
        return $this->createQueryBuilder('p')
            ->where('p.parent is null')
            ->andWhere('p.section = :section')
            ->setParameter('section', $section)
            ->orderBy('p.sortorder')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findOnNav() {
        return $this->createQueryBuilder('p')
            ->where('p.on_nav = :on_nav')
            ->setParameter('on_nav','1')
            ->getQuery()
            ->getSingleResult()
            ;
    }
}
