<?php

namespace English\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends EntityRepository
{
    /**
     * find pages for menu
     */
    public function findNewsletterSection()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT s  FROM EnglishPagesBundle:Section s WHERE s.name = ?1')
            ->setParameter('1','newsletter')->getSingleResult();
    }
}
