<?php

namespace English\GradcomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GradcomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradcomRepository extends EntityRepository
{
}